### ISSUE TITLE
Replicate PyTorch Functionality - Conv2d Layers

### ISSUE THREAD

**Issue by isotnek** [Beyond-ML-Labs/BeyondML#23]
PyTorch Conv2d layers take input & output size as parameters. BeyondML should replicate in its pt Conv2D layer to keep the syntax similar.

**Comment by jacobrenn** [comment]
PyTorch Con2D layers take in channels and out channels as a parameter (https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#torch.nn.Conv2d). The `Conv2D` layer in BeyondML is meant to be instantiated with existing trained weights. The `MaskedConv2D` layer is probably what you are looking for. It is instantiated with the same parameters of in and out channels (https://beyond-ml-labs.github.io/BeyondML/beyondml/pt/layers/MaskedConv2D.html).

**Comment by isotnek** [comment]
You're right, that was an oversight on my part. Thanks!
