### ISSUE TITLE
PyPI installs & upgrades to version 0.0.0 by default

### ISSUE THREAD

**Issue by isotnek** [Beyond-ML-Labs/BeyondML#37]
In a fresh conda environment on MacOS 13.0.1 with Python 3.10.8:

`pip install beyondml` installs beyondml version 0.0.0
`pip install beyondml --upgrade` reinstalls beyondml version 0.0.0

I can install newer versions by specifying the version, but ideally `pip install beyondml` would install the most recent stable version.

**Comment by jacobrenn** [comment]
Issue was related to Mac requiring TensorFlow installed before installing BeyondML
