### ISSUE TITLE
Looking for contribution

### ISSUE THREAD

**Issue by JaynouOliver** [Beyond-ML-Labs/BeyondML#44]
Hi, I am looking to learn and contribute in BeyondML, please let me know how do I proceeded

**Comment by jacobrenn** [comment]
Hi @JaynouOliver, thanks for your interest in learning and contributing to BeyondML.  Please find BeyondML's documentation site at this link: https://beyond-ml-labs.github.io/BeyondML/index.html.  We also have a GitHub repository that contains example use cases for using BeyondML.  That link is here: https://github.com/Beyond-ML-Labs/mann-notebooks.

After you have taken a look at those resources, please let us know how you would like to help contribute.  Thanks again!

**Comment by JaynouOliver** [comment]
Sure, I will get back shortly after going through everything, thanks a lot

**Comment by jacobrenn** [comment]
You are very welcome!
